### ISSUE TITLE
Adjust Testimonials

### ISSUE THREAD

**Issue by fyrworx4** [cpp-swift/WhatATheme#10]
Two testimonials side by side looks a bit weird, can we try top-bottom?

<img width="1252" alt="CleanShot 2022-03-15 at 19 29 08@2x" src="https://user-images.githubusercontent.com/5704805/158504683-5ba0e7ca-496e-4c2f-9611-2976a0b5eaf0.png">

**Comment by fyrworx4** [comment]
Also, testimonials is spelled wrong

**Comment by dbaseqp** [comment]
I think if we had more testimonials, the original card format works pretty well. Maybe we could make it so you can click on it to expand it? That would be really cool.
