### ISSUE TITLE
Tighten "Computer Networking, Cybersecurity, System Administration" section

### ISSUE THREAD

**Issue by fyrworx4** [cpp-swift/WhatATheme#4]
Is there a way to tighten the text in this section? Seems like it's too wide.

![CleanShot 2022-03-15 at 19 21 50@2x](https://user-images.githubusercontent.com/5704805/158503979-e71c526b-cefe-44dc-9334-9f16f349fa18.png)

**Comment by dbaseqp** [comment]
The columns don't react to different screen sizes. Need to make sure it is reactive.

**Comment by dbaseqp** [comment]
Straight up replaced three column design with sliding carousel in c3fbf47d9a0409bc0c55bd675b9958363b741110.
