### ISSUE TITLE
Left align the text underneath each section on homepage

### ISSUE THREAD

**Issue by fyrworx4** [cpp-swift/WhatATheme#5]
Text looks a bit wonky with justified margins.

![CleanShot 2022-03-15 at 19 24 03@2x](https://user-images.githubusercontent.com/5704805/158504181-7cc12c4e-b5df-4aba-8462-edb59fd820ee.png)

**Comment by dbaseqp** [comment]
Fixed in c3fbf47d9a0409bc0c55bd675b9958363b741110.
