### ISSUE TITLE
Adjust Steps

### ISSUE THREAD

**Issue by fyrworx4** [cpp-swift/WhatATheme#9]
Is there a way to make the steps bigger?

Also, joining SWIFT shouldn't be a step 1, step 2, step 3 process so maybe we should rethink how this page is formatted.

![CleanShot 2022-03-15 at 19 28 01@2x](https://user-images.githubusercontent.com/5704805/158504563-34b52e54-6595-4689-bd56-d12721430313.png)

**Comment by dbaseqp** [comment]
Fixed it in c3fbf47. Used flexboxes.

https://github.com/cpp-swift/WhatATheme/blob/c3fbf47d9a0409bc0c55bd675b9958363b741110/assets/css/style.scss#L329-L335
